name: Build and Deploy to github pages
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Deploy react app to github pages
    uses: tanwanimohit/deploy-react-to-ghpages@v1.0.1
      env:
        ACCESS_TOKEN: ${{ secrets.SAMEASTRAVIS }}
        BRANCH: gh-pages
        FOLDER: build
        BUILD_SCRIPT: npm install && npm run build

